In [4]:
!pip install deap update_checker tqdm stopit xgboost tpot

In [6]:
!wget = 'https://raw.githubusercontent.com/anmolduainter/Diagnostic-and-Prognostic-Breast-Cancer/master/Dataset/Diagnostic.txt'
!wget = 'https://raw.githubusercontent.com/anmolduainter/Diagnostic-and-Prognostic-Breast-Cancer/master/Dataset/Prognostic.txt'

--2018-03-01 18:08:18--  http://=/
Resolving = (=)... failed: Name or service not known.
wget: unable to resolve host address ‘=’
--2018-03-01 18:08:18--  https://raw.githubusercontent.com/anmolduainter/Diagnostic-and-Prognostic-Breast-Cancer/master/Dataset/Diagnostic.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 124103 (121K) [text/plain]
Saving to: ‘Diagnostic.txt’

Diagnostic.txt      100%[===================>] 121.19K  --.-KB/s    in 0.04s   

2018-03-01 18:08:18 (3.00 MB/s) - ‘Diagnostic.txt’ saved [124103/124103]

FINISHED --2018-03-01 18:08:18--
Total wall clock time: 0.2s
Downloaded: 1 files, 121K in 0.04s (3.00 MB/s)
--2018-03-01 18:08:19--  http://=/
Resolving = (=)... failed: Name or service not known.
wget: unable to resolve host address ‘=’
--2

In [7]:
!ls

datalab  Diagnostic.txt  Prognostic.txt


In [0]:
import numpy as np
import pandas as pd
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Diagnostic

In [0]:
diag = pd.read_csv('Diagnostic.txt' , sep = ',' , header = None)

In [16]:
diag.shape

(569, 32)

In [11]:
diag.head(3)

0  1      2      3      4       5        6        7       8   \
0    842302  M  17.99  10.38  122.8  1001.0  0.11840  0.27760  0.3001   
1    842517  M  20.57  17.77  132.9  1326.0  0.08474  0.07864  0.0869   
2  84300903  M  19.69  21.25  130.0  1203.0  0.10960  0.15990  0.1974   

        9    ...        22     23     24      25      26      27      28  \
0  0.14710   ...     25.38  17.33  184.6  2019.0  0.1622  0.6656  0.7119   
1  0.07017   ...     24.99  23.41  158.8  1956.0  0.1238  0.1866  0.2416   
2  0.12790   ...     23.57  25.53  152.5  1709.0  0.1444  0.4245  0.4504   

       29      30       31  
0  0.2654  0.4601  0.11890  
1  0.1860  0.2750  0.08902  
2  0.2430  0.3613  0.08758  

[3 rows x 32 columns]

In [20]:
X = diag.iloc[ : , 2:32 ].values
Y = diag.iloc[ : , 1].values
l = LabelEncoder()
Y = l.fit_transform(Y)
print (X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [22]:
tpot = TPOTClassifier(generations=5 , verbosity=2)
tpot.fit(X_train, y_train)

Optimization Progress:  33%|███▎      | 200/600 [01:56<06:46,  1.02s/pipeline]

Generation 1 - Current best internal CV score: 0.975725964856


Optimization Progress:  50%|█████     | 300/600 [03:54<03:37,  1.38pipeline/s]

Generation 2 - Current best internal CV score: 0.980122100122


Optimization Progress:  67%|██████▋   | 400/600 [05:54<02:24,  1.39pipeline/s]

Generation 3 - Current best internal CV score: 0.980122100122


Optimization Progress:  83%|████████▎ | 500/600 [09:26<01:08,  1.46pipeline/s]

Generation 4 - Current best internal CV score: 0.980122100122


Generation 5 - Current best internal CV score: 0.980122100122

Best pipeline: GradientBoostingClassifier(LogisticRegression(input_matrix, C=0.5, dual=True, penalty=l2), learning_rate=0.1, max_depth=5, max_features=0.8500000000000001, min_samples_leaf=19, min_samples_split=13, n_estimators=100, subsample=0.6500000000000001)


TPOTClassifier(config_dict={'sklearn.ensemble.GradientBoostingClassifier': {'max_features': array([0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55,
       0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]), 'learning_rate': [0.001, 0.01, 0.1, 0.5, 1.0], 'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7...  0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])}, 'sklearn.preprocessing.RobustScaler': {}},
        crossover_rate=0.1, cv=5, disable_update_check=False,
        early_stop=None, generations=5, max_eval_time_mins=5,
        max_time_mins=None, memory=None, mutation_rate=0.9, n_jobs=1,
        offspring_size=100, periodic_checkpoint_folder=None,
        population_size=100, random_state=None, scoring=None,
        subsample=1.0, verbosity=2, warm_start=False)

In [23]:
print(tpot.score(X_test, y_test))

0.9649122807017544


# Prognostic

In [0]:
prog = pd.read_csv('Prognostic.txt' , sep = ',' , header = None)

In [25]:
prog.shape

(198, 35)

In [26]:
X = prog.iloc[ : , 2:32 ].values
Y = prog.iloc[ : , 1].values
l = LabelEncoder()
Y = l.fit_transform(Y)
print (X)
print(Y)

[[3.100e+01 1.802e+01 2.760e+01 ... 3.140e-01 1.170e-01 2.677e-01]
 [6.100e+01 1.799e+01 1.038e+01 ... 7.119e-01 2.654e-01 4.601e-01]
 [1.160e+02 2.137e+01 1.744e+01 ... 3.414e-01 2.032e-01 4.334e-01]
 ...
 [1.200e+01 1.717e+01 2.919e+01 ... 2.141e-01 9.520e-02 3.362e-01]
 [3.000e+00 2.142e+01 2.284e+01 ... 5.411e-01 2.215e-01 2.832e-01]
 [6.000e+00 1.670e+01 2.813e+01 ... 3.455e-01 1.317e-01 3.035e-01]]
[0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1
 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1
 0 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0]


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [28]:
tpot = TPOTClassifier(generations=5 , verbosity=2)
tpot.fit(X_train, y_train)

Optimization Progress:  33%|███▎      | 200/600 [01:38<03:28,  1.92pipeline/s]

Generation 1 - Current best internal CV score: 0.7975


Optimization Progress:  50%|█████     | 300/600 [02:30<04:11,  1.19pipeline/s]

Generation 2 - Current best internal CV score: 0.798333333333


Optimization Progress:  67%|██████▋   | 400/600 [03:36<04:18,  1.29s/pipeline]

Generation 3 - Current best internal CV score: 0.804583333333


Optimization Progress:  83%|████████▎ | 500/600 [04:51<00:42,  2.36pipeline/s]

Generation 4 - Current best internal CV score: 0.823333333333


Generation 5 - Current best internal CV score: 0.823333333333

Best pipeline: ExtraTreesClassifier(PolynomialFeatures(input_matrix, degree=2, include_bias=False, interaction_only=False), bootstrap=True, criterion=entropy, max_features=0.55, min_samples_leaf=1, min_samples_split=17, n_estimators=100)


TPOTClassifier(config_dict={'sklearn.ensemble.GradientBoostingClassifier': {'max_features': array([0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55,
       0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]), 'learning_rate': [0.001, 0.01, 0.1, 0.5, 1.0], 'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7...  0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])}, 'sklearn.preprocessing.RobustScaler': {}},
        crossover_rate=0.1, cv=5, disable_update_check=False,
        early_stop=None, generations=5, max_eval_time_mins=5,
        max_time_mins=None, memory=None, mutation_rate=0.9, n_jobs=1,
        offspring_size=100, periodic_checkpoint_folder=None,
        population_size=100, random_state=None, scoring=None,
        subsample=1.0, verbosity=2, warm_start=False)

In [29]:
print(tpot.score(X_test, y_test))

0.85
